language: python
python:
  - "3.9"

branches:
  only:
    - docs
    - hotfix

install:
  - sudo apt-get install tree
  - gem install asciidoctor
  - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  - python get-pip.py
  - pip3 install Pygments
  - pip3 install -r scripts/requirements.txt
  - export PATH=~/.local/bin:$PATH
  - cd scripts
#  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then ./import_events.py; fi'
  - cd ..
  - rm -rf public || exit 0

script:
  - ./bin/hugo --buildFuture --verbose
  - cd public
  - touch .nojekyll
  - echo "redhatgov.io" > CNAME
  - tree workshops
  - tree events
  - cd ..
  - pwd

deploy:
  provider: pages
  local-dir: public
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  target-branch: master
  verbose: true
  on:
    branch: docs

notifications:
  slack: redhat:9meDz4fnYsXtr3krfjmSXADX
  email:
    - ajacocks@redhat.com
